#!/bin/bash

# Script that outputs disk space taken up by files
# and dirs in current dir or in path as arg
# Anish Sujanani, December 2022

d=$1

if [ "$#" -ne 1 ]; then
	d="."
fi

du -h -s $(readlink -f $d)/* | sort -r -h | column -t
